name: common
description: Demo common widgets and utils
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive_assets:
    path: ../hive_assets
  dimensions_theme: ^0.0.2+1
  flutter_screenutil: ^5.6.1
  fluttertoast: ^8.2.2
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  animated_custom_dropdown: ^3.1.1


dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

